name: Pipeline de CI/CD para Atividade de DevOps

on:
  push:
    branches:
      - master  # Executa o workflow em pushes para o branch principal
  pull_request:
    branches:
      - master  # Executa o workflow em pull requests para o branch principal

jobs:
  build:
    runs-on: ubuntu-latest  # Define que o job será executado em um ambiente Ubuntu
    steps:
    - name: Verificar Código
      uses: actions/checkout@v2  # Busca o código do repositório

    - name: Construir Imagem Docker
      run: docker build -t app-mensagens-pucpr .  # Constrói a imagem Docker da aplicação

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push Docker Image to Docker Hub
      run: |
        docker tag app-mensagens-pucpr ${{ secrets.DOCKER_USERNAME }}/app-mensagens-pucpr:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/app-mensagens-pucpr:latest
      # Envia a imagem Docker para o Docker Hub

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Executar Ferramenta SAST
      uses: SonarSource/sonarcloud-github-action@master
      with:
        args: >
          -Dsonar.projectKey=bruvini_Somativa2DEVOPSBruno
          -Dsonar.organization=bruvini
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}  # Usa o token do SonarCloud como variável de ambiente
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Usa o token do GitHub como variável de ambiente

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - name: Deploy no Vercel
      run: echo "Deploy realizado com sucesso! Acesse a aplicação em https://somativa2-devops-bruno.vercel.app/ via integração com Vercel"
      # Mensagem de confirmação de deploy no Vercel

    - name: Notificar Discord
      run: |
        curl -X POST -H "Content-Type: application/json" \
             -d "{\"content\": \"Ação realizada no GitHub: ${{ github.event_name }}, veja mais em: ${{ github.event.pull_request.html_url || 'https://somativa2-devops-bruno.vercel.app/' }}\"}" \
             ${{ secrets.DISCORD_WEBHOOK_URL }}
      # Usa o webhook do Discord para enviar uma notificação sobre a ação realizada
